/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_apress_MainActivity_PlayTast */

#ifndef _Included_com_example_apress_MainActivity_PlayTast
#define _Included_com_example_apress_MainActivity_PlayTast
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
